apiVersion: v1
kind: Service
metadata:
  name: tx-node
  labels:
    app: geth
    type: tx
spec:
  ports:
    # the port that this service should serve on
  - port: 8545
    targetPort: 8545
    name: tcp-8545
  - port: 8546
    targetPort: 8546
    name: tcp-8546
  - port: 30303
    targetPort: 30303
    name: tcp-30303
  - port: 30303
    targetPort: 30303
    name: udp-30303
    protocol: UDP
  selector:
    app: geth
    type: tx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tx-node
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: geth
        type: tx
    spec:
      containers:
      - name: tx
        image: wbuchwalter/tx-node
        ports:
        - containerPort: 8545
        - containerPort: 8546
        - containerPort: 30303
---
apiVersion: v1
kind: Service
metadata:
  name: miner-node
  labels:
    app: geth
    type: miner
spec:
  ports:
    # the port that this service should serve on
  - port: 8545
    targetPort: 8545
    name: tcp-8545
  - port: 8546
    targetPort: 8546
    name: tcp-8546
  - port: 30303
    targetPort: 30303
    name: tcp-30303
  - port: 30303
    targetPort: 30303
    name: udp-30303
    protocol: UDP
  selector:
    app: geth
    type: miner
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: miner-node
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: geth
        type: miner
    spec:
      containers:
      - name: miner
        image: wbuchwalter/miner-node
        ports:
        - containerPort: 8545
        - containerPort: 8546
        - containerPort: 30303