apiVersion: v1
kind: Service
metadata:
  name: tx-node
  labels:
    app: geth
    type: tx
spec:
  ports:
  - port: 8545
    targetPort: 8545
    name: tcp-8545
  - port: 8546
    targetPort: 8546
    name: tcp-8546
  - port: 30303
    targetPort: 30303
    name: tcp-30303
  - port: 30303
    targetPort: 30303
    name: udp-30303
    protocol: UDP
  selector:
    app: geth
    type: tx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tx-node
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: geth
        type: tx
    spec:
      containers:
      - name: tx
        image: wbuchwalter/geth-node
        ports:
        - containerPort: 8545
        - containerPort: 8546
        - containerPort: 30303
        env:
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NETWORKID
          value: "20170216"
        - name: WS_SERVER
          value: ws://dashboard:3000
        - name: WS_SECRET
          value: Bistro12345!
        - name: BOOTNODE_URL
          value: http://dashboard:3001
        - name: BOOTNODE_NETWORK
          value: network_1
        - name: BOOTNODE_PUBLIC_IP
          value: dashboard