---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
  labels:
    app:  dashboard
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: tcp-3000
  - port: 3001
    targetPort: 3001
    name: tcp-3001
  selector:
    app: dashboard
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dashboard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
      - name: dashboard
        image: ethereumex/eth-stats-dashboard
        ports:
        - containerPort: 3000
        - containerPort: 3001
        env:
        - name: WS_SECRET
          value: Bistro12345!
